source 'https://rubygems.org'

gem 'sinatra'
gem 'crack'
gem 'haml'
gem 'sqlite3'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'sass'
gem 'shotgun'
gem 'nokogiri'
gem 'awesome_print'
gem 'whenever'